spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
github:
  client:
    id: "7768e7e66f0af96f2ca4"
    secret: "e1c115a50917e221104ddc0e368b268f92ce4345"
  redirect_uri: "http://localhost:8080/callback"
pagehelper:
    helperDialect: mysql