spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
mybatis:
  mapper-locations: classpath:mapper/*.xml
github:
  client:
    id: "7768e7e66f0af96f2ca4"
    secret: ENC(sRLVmUwej8VM+h7KuUrH60oYq/pE0d+SAJzkBYekGjG29Mr4BXa8wPr1W+HWxDTChvvO7KH4h9A=)
  redirect_uri: "http://localhost:8080/callback"
pagehelper:
    helperDialect: mysql
jasypt:
  encryptor:
    password: codenotes
