spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
mybatis:
  mapper-locations: classpath:mapper/*.xml
github:
  client:
    id: "7768e7e66f0af96f2ca4"
    secret: "e1c115a50917e221104ddc0e368b268f92ce4345"
  redirect_uri: "http://localhost:8080/callback"
pagehelper:
    helperDialect: mysql
qiniu:
  access_token: "1ZeKAOLvjpBCvvMBxOLrWFf-vyCIYEuFdAaDIJ6t"
  secret_token: "2nEYuPTdZMLe5yA6hWkscQ3DPfkqag1jUEsf0x1J"
  bucket: "conotes"
  domain_of_bucket: "http://cdn.conotes.cn"