spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.fred.blog.codenotes: debug
  file:
    path: log/blog-dev.log
    max-size: 10MB
    max-history: 7
server:
  port: 8080
github:
  client:
    id: "7768e7e66f0af96f2ca4"
    secret: "e1c115a50917e221104ddc0e368b268f92ce4345"
  redirect_uri: "http://localhost:8080/callback"