spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
github:
  client:
    id: "7768e7e66f0af96f2ca4"
    secret: "e1c115a50917e221104ddc0e368b268f92ce4345"
  redirect_uri: "http://localhost:8080/callback"
pagehelper:
    helperDialect: mysql
qiniu:
  access_token: "1ZeKAOLvjpBCvvMBxOLrWFf-vyCIYEuFdAaDIJ6t"
  secret_token: ENC(D5UN62tamDB80vMas25J/FBSKXcPd2wvkem0ZunKputiiHDtiJ0Ft8mmwrMM5iegjKt7WY17THo=)
  bucket: "conotes"
  domain_of_bucket: "http://cdn.conotes.cn"
