spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    root: info
    com.fred.blog.codenotes: debug
  file:
    path: log/blog-dev.log
    max-size: 10MB
    max-history: 7
server:
  port: 8080
jasypt:
  encryptor:
    password: codenotes